### ISSUE TITLE
类似黑客客户端内右上方的ArrayList,展示已经开启的功能

### ISSUE THREAD

**Issue by ImCZFy** [LEFgangaDEV/Nov-PVP#1]
就像黑客端右上方写着的哪些啥Killaura Velocity之类的，这个建议的确有点奇葩3333如果觉得不太好就拒绝吧，如果觉得还可以，请记得加一个开关2333， 辛苦了

**Comment by LEFgangaDEV** [comment]
okay,but why do you want to add that

**Comment by LEFgangaDEV** [comment]
remove to Gitee
